# Generated by Django 4.0.1 on 2022-02-15 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_de', models.CharField(blank=True, max_length=50)),
                ('country_en', models.CharField(blank=True, max_length=50)),
                ('country_sr', models.CharField(max_length=50)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='countries')),
                ('continent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.continents')),
            ],
        ),
    ]
